name: Renovate
on: workflow_dispatch
jobs:
  renovate:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.7
        with:
          docker-cmd-file: .github/renovate-entrypoint.sh
          docker-user: root
          token: ${{ secrets.PRIVATE_ACCESS_TOKEN }}
          
    
      # - name: Setup renovate
      #   run: npm install -g renovate@32.89.0

      # - name: Run renovate
      #   env:
      #     RENOVATE_REPOSITORIES: ${{ vars.RENOVATE_REPOSITORIES }}
      #     RENOVATE_TOKEN: ${{ secrets.PRIVATE_ACCESS_TOKEN }}
      #     RENOVATE_ALLOW_POST_UPGRADE_COMMAND_TEMPLATING: true
      #     RENOVATE_ALLOWED_POST_UPGRADE_COMMANDS: ".*"
      #   run: renovate
