name: Renovate
on: workflow_dispatch
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: tibdex/github-app-token@v1
        with:
          private_key: ${{ secrets.PRIVATE_KEY }}
          app_id: ${{ secrets.APP_ID }}

      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v34.84.2
        with:
          configurationFile: .github/renovate.json
          token: '${{ steps.get_token.outputs.token }}'
          # token: 'x-access-token:${{ steps.get_token.outputs.token }}'
        env:
          RENOVATE_USERNAME: ${{ vars.RENOVATE_USERNAME }}
          RENOVATE_GIT_AUTHOR: ${{ vars.RENOVATE_GIT_AUTHOR }}
          RENOVATE_REPOSITORIES: ${{ vars.RENOVATE_REPOSITORIES }}
          RENOVATE_GIT_EMAIL: ${{ vars.RENOVATE_GIT_EMAIL }}
  # renovate:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Get token
  #       id: get_token
  #       uses: tibdex/github-app-token@v1
  #       with:
  #         private_key: ${{ secrets.PRIVATE_KEY }}
  #         app_id: ${{ secrets.APP_ID }}
  #     - name: Set up Git configuration
  #       run: |
  #         git config --global user.email "875925kenta-test-app@users.noreply.github.enterprise.com"
  #         git config --global user.name "kenta-test-app"

  #     - name: Checkout
  #       uses: actions/checkout@v4.1.1
  #     - name: Self-hosted Renovate
  #       uses: renovatebot/github-action@v40.1.7
  #       with:
  #         configurationFile: .github/renovate.json
  #         token: 'x-access-token:${{ steps.get_token.outputs.token }}'
  #       env:
  #         RENOVATE_USERNAME: ${{ vars.RENOVATE_USERNAME }}
  #         RENOVATE_GIT_AUTHOR: ${{ vars.RENOVATE_GIT_AUTHOR }}
  #         RENOVATE_REPOSITORIES: ${{ vars.RENOVATE_REPOSITORIES }}
  #         RENOVATE_ALLOW_POST_UPGRADE_COMMAND_TEMPLATING: true
  #         RENOVATE_ALLOWED_POST_UPGRADE_COMMANDS: ".*"
      # - name: Setup renovate
      #   run: npm install -g renovate@32.89.0

      # - name: Run renovate
      #   env:
      #     RENOVATE_REPOSITORIES: ${{ vars.RENOVATE_REPOSITORIES }}
      #     RENOVATE_TOKEN: ${{ secrets.PRIVATE_ACCESS_TOKEN }}
      #     RENOVATE_ALLOW_POST_UPGRADE_COMMAND_TEMPLATING: true
      #     RENOVATE_ALLOWED_POST_UPGRADE_COMMANDS: ".*"
      #   run: renovate
