name: Renovate
on: workflow_dispatch
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: tibdex/github-app-token@v1
        with:
          private_key: ${{ secrets.PRIVATE_KEY }}
          app_id: ${{ secrets.APP_ID }}

      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.9
        with:
          configurationFile: .github/renovate.json
          token: 'x-access-token:${{ steps.get_token.outputs.token }}'
        env:
          RENOVATE_USERNAME: ${{ vars.RENOVATE_USERNAME }}
          RENOVATE_GIT_AUTHOR: ${{ vars.RENOVATE_GIT_AUTHOR }}
          RENOVATE_REPOSITORIES: ${{ vars.RENOVATE_REPOSITORIES }}
    # runs-on: ubuntu-latest

    # steps:
    #   - name: Get token
    #     id: get_token
    #     uses: tibdex/github-app-token@v1
    #     with:
    #       private_key: ${{ secrets.PRIVATE_KEY }}
    #       app_id: ${{ secrets.APP_ID }}
          
    #   - name: Checkout
    #     uses: actions/checkout@v4.1.1

    #   - name: Self-hosted Renovate
    #     uses: renovatebot/github-action@v40.1.7
    #     with:
    #       token: '${{ steps.get_token.outputs.token }}'
    #       # token: ${{ secrets.RENOVATE_TOKEN }}
    #     env:
    #       RENOVATE_USERNAME: ${{ vars.RENOVATE_USERNAME }}
    #       # RENOVATE_PLATFORM: 'github'
    #       RENOVATE_REPOSITORIES: ${{ vars.RENOVATE_REPOSITORIES }}
