name: Renovate
on: workflow_dispatch
jobs:
  renovate:
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@v1
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
          app-id: ${{ secrets.APP_ID }}
        # uses: tibdex/github-app-token@v2
        # with:
        #   private_key: ${{ secrets.PRIVATE_KEY }}
        #   app_id: ${{ secrets.APP_ID }}

      - name: Checkout
        uses: actions/checkout@v4.1.1
      # renovatebot で動かす場合はこちら
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.9
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.PRIVATE_ACCESS_TOKEN }}
          # token: ${{ steps.get_token.outputs.token }}
        env:
          RENOVATE_USERNAME: ${{ vars.RENOVATE_USERNAME }}
          RENOVATE_REPOSITORIES: ${{ vars.RENOVATE_REPOSITORIES }}


      # renovate をインストールした動かす場合はこちら
      # - name: Setup renovate
      #   run: npm install -g renovate@latest

      # - name: Run renovate
      #   env:
      #     RENOVATE_REPOSITORIES: ${{ vars.RENOVATE_REPOSITORIES }}
      #     RENOVATE_TOKEN: ${{ steps.get_token.outputs.token }}
      #     # RENOVATE_ALLOW_POST_UPGRADE_COMMAND_TEMPLATING: true
      #     # RENOVATE_ALLOWED_POST_UPGRADE_COMMANDS: ".*"
      #   run: renovate
